# Generated by Django 2.1.2 on 2018-10-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFeatureUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('new_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
        ),
    ]
