# Generated by Django 2.1.1 on 2018-09-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[('TODO', 'To do'), ('DOING', 'In process'), ('DONE', 'Done')], default='TODO'),
        ),
    ]
