# Generated by Django 2.1.1 on 2018-09-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180920_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('TODO', 'To do'), ('DOING', 'In process'), ('DONE', 'Done')], default='TODO', max_length=10),
        ),
    ]
