# Generated by Django 2.1.1 on 2018-10-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticketcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketcomment',
            old_name='for_ticket',
            new_name='ticket',
        ),
    ]
