# Generated by Django 2.1.1 on 2018-10-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_auto_20181001_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
