# Generated by Django 2.1.1 on 2018-10-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20181001_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='upvotes',
        ),
    ]
