# Generated by Django 2.1.2 on 2018-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_ticket_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payments',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
